export const INCREMENT_COUNTER = "INCREMENT_COUNTER"
export const DEREMENT_COUNTER = "DEREMENT_COUNTER"
export const PRODUCT_GETDATA = "PRODUCT_GETDATA"

export const LOADING_PRODUCT = "LOADING_PRODUCT"
export const ERROR_PRODUCT = "ERROR_PRODUCT"