export const INCREMENT_COUNTER = "INCREMENT_COUNTER"
export const DEREMENT_COUNTER = "DEREMENT_COUNTER"
export const PRODUCT_GETDATA = "PRODUCT_GETDATA"

export const LOADING_PRODUCT = "LOADING_PRODUCT"
export const ERROR_PRODUCT = "ERROR_PRODUCT"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const ADD_PRODUCT = "ADD_PRODUCT"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"

export const GETDATA_CATEGORY = "GETDATA_CATEGORY"
export const ERROR_CATEGORY = "ERROR_CATEGORY"
export const ADD_CATEGORY = "ADD_CATEGORY"
